"use client";
import {useEffect,useMemo,useState} from "react";
import AppNav from "@/components/AppNav";
import {createClient} from "@/lib/supabase/client";
type Pref={min_age:number;max_age:number;max_distance_miles:number;genders:string[];relationship_types:string[];wants_children:string};
const blank:Pref={min_age:18,max_age:99,max_distance_miles:50,genders:[],relationship_types:[],wants_children:"No preference"};
const genderOptions=["Woman","Man","Nonbinary"];
const goals=["Long-term relationship","Dating with intention","Open to exploring","Friendship first"];
export default function PreferencesPage(){
 const supabase=useMemo(()=>createClient(),[]);const [p,setP]=useState(blank);const [notice,setNotice]=useState("");const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setNotice("Please sign in.");setLoading(false);return;}const {data,error}=await supabase.from("preferences").select("*").eq("user_id",user.id).maybeSingle();if(error)setNotice(error.message);if(data)setP({...blank,...data,genders:data.genders||[],relationship_types:data.relationship_types||[]});setLoading(false)})()},[supabase]);
 const toggle=(key:"genders"|"relationship_types",v:string)=>setP(x=>({...x,[key]:x[key].includes(v)?x[key].filter(i=>i!==v):[...x[key],v]}));
 async function save(){if(p.min_age<18||p.max_age<p.min_age)return setNotice("Please choose a valid age range starting at 18.");const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from("preferences").upsert({user_id:user.id,...p,updated_at:new Date().toISOString()});setNotice(error?error.message:"Dating preferences saved.");}
 return <main><AppNav/><section className="appPage narrow"><div className="eyebrow">Preferences</div><h1>Who would you like to meet?</h1><p className="sectionIntro">These settings guide your Discover feed. Recovery, mental-health and assessment information stays under its own privacy controls.</p>{notice&&<p className="saveNotice">{notice}</p>}{loading?<p>Loading...</p>:<div className="editProfileCard"><div className="editGrid"><label>Minimum age<input type="number" min="18" max="99" value={p.min_age} onChange={e=>setP(x=>({...x,min_age:Number(e.target.value)}))}/></label><label>Maximum age<input type="number" min="18" max="99" value={p.max_age} onChange={e=>setP(x=>({...x,max_age:Number(e.target.value)}))}/></label><label>Distance preference (miles)<input type="number" min="1" max="500" value={p.max_distance_miles} onChange={e=>setP(x=>({...x,max_distance_miles:Number(e.target.value)}))}/><small>Saved for your preference. Exact-distance filtering is not used until location support is available.</small></label><label>Children preference<select value={p.wants_children} onChange={e=>setP(x=>({...x,wants_children:e.target.value}))}><option>No preference</option><option>Want children</option><option>Do not want children</option><option>Open to children</option></select></label><div className="fullField"><strong>Gender preferences</strong>{genderOptions.map(v=><label className="claimConsent" key={v}><input type="checkbox" checked={p.genders.includes(v)} onChange={()=>toggle("genders",v)}/><span>{v}</span></label>)}</div><div className="fullField"><strong>Relationship goals</strong>{goals.map(v=><label className="claimConsent" key={v}><input type="checkbox" checked={p.relationship_types.includes(v)} onChange={()=>toggle("relationship_types",v)}/><span>{v}</span></label>)}</div></div><button className="primaryButton" onClick={save}>Save preferences</button></div>}</section></main>;
}